CREATE DATABASE ECOM; -- creating database
USE ECOM;	-- using the database

-- creating tables
-- customers

CREATE TABLE CUSTOMERS(
CUST_ID VARCHAR(255),
FIRST_NAME VARCHAR(250),
LAST_NAME VARCHAR(255),
EMAIL VARCHAR(250),
GENDER ENUM("Male","Female","Others"),
PHONE VARCHAR(10),
ANNUAL_INCOME DECIMAL(10,2));

SELECT * 
FROM CUSTOMERS;

DESCRIBE CUSTOMERS;

-- PRODUCT TABLE

CREATE TABLE PRODUCTS(
PROD_ID INT PRIMARY KEY,
PROD_NAME VARCHAR(255) UNIQUE,
UNIT_PRICE DECIMAL(10,2),
CATEGORY VARCHAR(200));

ALTER TABLE CUSTOMERS
MODIFY COLUMN  CUST_ID VARCHAR(255) PRIMARY KEY;

DESCRIBE CUSTOMERS;

-- SALES TABLE

CREATE TABLE SALES(
QUANTITY INT,
SALES DECIMAL(9,2),
CUST_ID VARCHAR(200),
PROD_ID INT,
DISCOUNT DECIMAL(3,2),
LOCATION CHAR(50),
ORDER_DATE DATE,
DELIVERY_DATE DATE,
PROFIT DECIMAL(9,2));

ALTER TABLE SALES
ADD CONSTRAINT FOREIGN KEY (CUST_ID) REFERENCES CUSTOMERS(CUST_ID),
ADD CONSTRAINT FOREIGN KEY (PROD_ID) REFERENCES PRODUCTS(PROD_ID);

DESCRIBE SALES;

-- INSERTING DATA ON CUSTOMERS

INSERT INTO CUSTOMERS(CUST_ID,FIRST_NAME,LAST_NAME,EMAIL,GENDER,PHONE,ANNUAL_INCOME)
VALUES
("CUST-101","Veena","Kutty","veena.kutty@gmail.com","Female","1234567890",55000);

INSERT INTO CUSTOMERS VALUES
("CUST-102","Alex",NULL,"alex@gmail.com","Male","0987654321",50000),
("CUST-103","Alice","George",NULL,"Female","9088989765",75000),
("CUST-104","Ram","Patel","ram.patel@gmail.com","Male",NULL,60000),
("CUST-105","Hitesh","Hirwani","hitesh.hirwani@gmail.com","Male","656563473",65000);

SELECT *
FROM CUSTOMERS;

SELECT FIRST_NAME,GENDER
FROM CUSTOMERS;

-- Modify Tables

ALTER TABLE SALES
ADD COLUMN SALE_ID INT AUTO_INCREMENT PRIMARY KEY;

ALTER TABLE CUSTOMERS
MODIFY COLUMN FIRST_NAME VARCHAR(255) NOT NULL;

ALTER TABLE PRODUCTS
MODIFY COLUMN PROD_NAME VARCHAR(255) NOT NULL,
MODIFY COLUMN UNIT_PRICE DECIMAL(10,2) NOT NULL;